### ISSUE TITLE
Install PL-PHP on windows

### ISSUE THREAD

**Issue by farhanrashad** [commandprompt/PL-php#1]
i want to install PL-PHP on windows, what is the procedure.

**Comment by alexeyklyukin** [comment]
I'm not sure it's even possible. You can try building a custom PHP with embed on Windows (as described in the INSTALL file), installing it and then use --with-php option to point PL/php to the place PHP has been installed. You'd need some GNU environment on Windows (i.e. mingw, look here on how to install it: http://www.postgresql.org/docs/current/static/install-windows.html). But given the latest commit date of August 2012 and no major changes since 2011 I'd suggest looking somewhere else, i.e. PL/Python or PL/Perl, both are known to work with Windows.
